# Proxmox authentication
proxmox_url = "https://edge-pve-01.lan.homelab:8006/api2/json"

# Clone
# This is just a test, full_clone = false will speed up the process.
full_clone = false
clone_vm   = "ubuntu-24-04-server-raw"

# General
node                 = "edge-pve-02"
vm_id                = 905
vm_name              = "ubuntu-24-04-server-multi-networks"
template_description = "Ubuntu server 24.04.2 template with multiple network adapters generated by Packer on {{ isotime `2006-01-02 15:04` }}."

# Networks
network_adapters = [
  {
    bridge = "vmbr100"
  },
  {
    bridge   = "vmbr101"
    firewall = true
  },
  {
    bridge   = "vmbr2"
    model    = "virtio"
    vlan_tag = "100"
    firewall = false
  }
]
