proxmox_url          = "https://pve-01.lan.homelab:8006/api2/json"
node                 = "pve-02"
vm_id                = 911
build_name           = "ubuntu"
vm_name              = "ubuntu-24-04-server-standard"
clone_vm             = "ubuntu-24-04-server-raw"
template_description = "Ubuntu server 24.04 template with the default configuration generated by Packer on {{ isotime `2006-01-02` }}."
