# Proxmox authentication
proxmox_url = "https://pve-01.lan.homelab:8006/api2/json"

# General
node                 = "pve-01"
vm_id                = 911
vm_name              = "ubuntu-24-04-server-standard"
clone_vm             = "ubuntu-24-04-server-raw"
pool                 = "Template"
template_description = "Ubuntu server 24.04.2 template with the default configuration generated by Packer on {{ isotime `2006-01-02 15:04` }}."

# Cloud-Init
cloud_init_storage_pool = "Ceph_Gold"
