# Proxmox authentication
proxmox_url = "https://edge-pve-01.lan.homelab:8006/api2/json"

# Clone
# This is just a test, full_clone = false will speed up the process.
# full_clone = false
clone_vm = "ubuntu-24-04-server-raw"

# General
node                 = "edge-pve-01"
vm_id                = 904
vm_name              = "ubuntu-24-04-server-multiple-disks"
template_description = "Ubuntu server 24.04.2 template with multiple disks generated by Packer on {{ isotime `2006-01-02 15:04` }}."

# Hard Disk
disks = [
  {
    storage_pool = "Ceph_Gold"
  },
  {
    storage_pool = "Ceph_Gold"
    disk_size    = "20G"
  },
  {
    storage_pool = "Ceph_Gold"
    cache_mode   = "directsync"
    io_thread    = false
    discard      = false
    ssd          = false
  },
  {
    storage_pool = "Ceph_Gold"
    type         = "scsi"
    format       = "raw"
    disk_size    = "10G"
    cache_mode   = "none"
    io_thread    = true
    discard      = true
    ssd          = true
  }
]
