# Proxmox authentication
proxmox_url = "https://edge-pve-01.lan.homelab:8006/api2/json"

# Clone
# This is just a test, full_clone = false will speed up the process.
full_clone = false
clone_vm   = "ubuntu-24-04-server-raw"

# General
node                 = "edge-pve-01"
vm_id                = 902
vm_name              = "ubuntu-24-04-server-cpu"
template_description = "Ubuntu server 24.04.2 template with cpu modifications generated by Packer on {{ isotime `2006-01-02 15:04` }}."

# CPU
sockets  = 1
cores    = 2
cpu_type = "host"
