# Proxmox authentication
proxmox_url = "https://edge-pve-01.lan.homelab:8006/api2/json"

# Clone
# This is just a test, full_clone = false will speed up the process.
full_clone = false
clone_vm   = "ubuntu-24-04-server-raw"

# General
node                 = "edge-pve-02"
vm_id                = 903
vm_name              = "ubuntu-24-04-server-memory"
template_description = "Ubuntu server 24.04.2 template optimized for performance generated by Packer on {{ isotime `2006-01-02 15:04` }}."

# Memory
memory             = 16384 # 16 GB
ballooning_minimum = 4096  # 4 GB
