---
- name: "Changing the hostname"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/os/hostname"

- name: "Installing required packages"
  ansible.builtin.import_tasks: "installing-packages.yml"

- name: "Setting up the Firewall UFW"
  ansible.builtin.import_tasks: "ufw.yml"

- name: "Setting up fail2ban"
  ansible.builtin.import_tasks: "fail2ban.yml"

- name: "Removing unnecessary packages"
  ansible.builtin.import_tasks: "removing-packages.yml"

- name: "Recreating the machine-id file so the new VM can get a new IP"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/os/machine-id"

- name: "Removing unnecessary files, folders and configuration"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/os/clean-up"
