---
- name: "Setting up IPV4 as the default rule"
  ansible.builtin.lineinfile:
    path: "/etc/default/ufw"
    regexp: "IPV6="
    line: "IPV6=no"
    state: "present"

- name: "Ensure the ufw.log file exists"
  ansible.builtin.file:
    path: "/var/log/ufw.log"
    state: "touch"
    owner: "syslog"
    group: "syslog"
    mode: "0664"

- name: "Adding UFW rules"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/os/ufw-configure-rule"
  vars:
    rules: "{{ ufw.rules }}"

- name: "Setting DENY as the default policy and enabling the UFW"
  community.general.ufw:
    policy: "deny"
    state: "enabled"
